# authendication credintials
credentials:
  usernames:
    mainuddin:
      email: salma99hossain@mail.com
      name: salma
      password: $2b$12$Vya.5Gw0ur0pDxsjt22/suzsNMS/xXYti30GXZZFQ62nUWwmcLJFm # Placeholder for hashed password of 'abc'

cookie:
  expiry_days: 1
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
    - salma99hossain@gmail.com

db:
  host: "localhost"
  user: "root"
  passwd: "hasanctg50419"
  database: "ExpenseDB"
  auth_plugin: "mysql_native_password"

email_sender:
  email: "salma99hossain@gmail.com"
  pass: "1234"
